# Generated by Django 3.0.8 on 2023-06-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam_entry_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_point', models.CharField(max_length=128, verbose_name='考点')),
                ('exam_time', models.CharField(max_length=128, verbose_name='考试时间')),
                ('number', models.IntegerField(verbose_name='容量')),
                ('entry_number', models.IntegerField(default=0, verbose_name='已报名数量')),
            ],
            options={
                'verbose_name': '考点',
                'verbose_name_plural': '考点信息表',
            },
        ),
        migrations.CreateModel(
            name='paper_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.TextField(verbose_name='阅读文章')),
                ('writing', models.TextField(verbose_name='作文题目')),
                ('translation', models.TextField(verbose_name='翻译文本')),
            ],
        ),
        migrations.CreateModel(
            name='single_choose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=0, max_length=11, verbose_name='试卷编号')),
                ('qu_type', models.CharField(choices=[('listening', '听力'), ('reading', '阅读')], default='听力', max_length=32, verbose_name='题目类型')),
                ('qu', models.CharField(max_length=255, null=True)),
                ('A', models.CharField(default=' ', max_length=255)),
                ('B', models.CharField(default=' ', max_length=255)),
                ('C', models.CharField(default=' ', max_length=255)),
                ('D', models.CharField(default=' ', max_length=255)),
                ('ans', models.CharField(default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('user_true_name', models.CharField(max_length=128, null=True, verbose_name='真实姓名')),
                ('user_id', models.CharField(max_length=18, null=True, verbose_name='身份证号')),
                ('user_school', models.CharField(max_length=128, verbose_name='在读学校')),
                ('user_f_score', models.CharField(choices=[('fail', '未通过'), ('pass', '通过')], default='未通过', max_length=32, verbose_name='四级成绩')),
            ],
            options={
                'verbose_name': '用户名',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='user_entry_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', '待缴费'), ('payed', '待考试'), ('examed', '待批改'), ('corrected', '已出分')], default='待缴费', max_length=32, verbose_name='考试状态')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('ID_card', models.CharField(default=' ', max_length=18, verbose_name='身份证号')),
                ('exam_time', models.CharField(default=' ', max_length=128, verbose_name='考试时间')),
                ('exam_point', models.CharField(max_length=128, verbose_name='考点')),
                ('writing', models.IntegerField(default=0, verbose_name='写作')),
                ('listening', models.IntegerField(default=0, verbose_name='听力')),
                ('reading', models.IntegerField(default=0, verbose_name='阅读')),
                ('total', models.IntegerField(default=0, verbose_name='总分')),
                ('wri_ans', models.TextField(default=' ', verbose_name='作文答案')),
                ('tran_ans', models.TextField(default=' ', verbose_name='翻译答案')),
            ],
            options={
                'verbose_name': '用户考试信息',
                'verbose_name_plural': '用户考试信息表',
            },
        ),
    ]
