# Generated by Django 3.2.13 on 2023-06-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paper_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.TextField(verbose_name='阅读文章')),
                ('writing', models.TextField(verbose_name='作文题目')),
                ('translation', models.TextField(verbose_name='翻译文本')),
            ],
        ),
        migrations.CreateModel(
            name='single_choose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=0, max_length=11, verbose_name='试卷编号')),
                ('qu_type', models.CharField(choices=[('listening', '听力'), ('reading', '阅读')], default='听力', max_length=32, verbose_name='题目类型')),
                ('qu', models.CharField(max_length=255, null=True)),
                ('A', models.CharField(default=' ', max_length=255)),
                ('B', models.CharField(default=' ', max_length=255)),
                ('C', models.CharField(default=' ', max_length=255)),
                ('D', models.CharField(default=' ', max_length=255)),
                ('ans', models.CharField(default='A', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam_entry_table',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='exam_entry_table',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='user_s_score',
        ),
        migrations.RemoveField(
            model_name='user_entry_table',
            name='exam_id',
        ),
        migrations.AddField(
            model_name='user_entry_table',
            name='ID_card',
            field=models.CharField(default=' ', max_length=18, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='user_entry_table',
            name='exam_time',
            field=models.CharField(default=' ', max_length=128, verbose_name='考试时间'),
        ),
        migrations.AddField(
            model_name='user_entry_table',
            name='listening',
            field=models.IntegerField(default=0, verbose_name='听力'),
        ),
        migrations.AddField(
            model_name='user_entry_table',
            name='reading',
            field=models.IntegerField(default=0, verbose_name='阅读'),
        ),
        migrations.AddField(
            model_name='user_entry_table',
            name='total',
            field=models.IntegerField(default=0, verbose_name='总分'),
        ),
        migrations.AddField(
            model_name='user_entry_table',
            name='writing',
            field=models.IntegerField(default=0, verbose_name='写作'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='user_f_score',
            field=models.CharField(choices=[('fail', '未通过'), ('pass', '通过')], default='未通过', max_length=32, verbose_name='四级成绩'),
        ),
    ]
