# Generated by Django 3.0.8 on 2023-05-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_entry_table',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='user_s_score',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='user_f_score',
            field=models.CharField(choices=[('fail', '未通过'), ('pass', '通过')], default='未通过', max_length=32, verbose_name='四级成绩'),
        ),
    ]
