# Generated by Django 3.0.8 on 2023-06-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230531_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_entry_table',
            name='exam_time',
            field=models.CharField(default=' ', max_length=128, verbose_name='考试时间'),
        ),
        migrations.AddField(
            model_name='user_entry_table',
            name='listening',
            field=models.IntegerField(default=0, verbose_name='听力'),
        ),
        migrations.AddField(
            model_name='user_entry_table',
            name='reading',
            field=models.IntegerField(default=0, verbose_name='阅读'),
        ),
        migrations.AddField(
            model_name='user_entry_table',
            name='total',
            field=models.IntegerField(default=0, verbose_name='总分'),
        ),
        migrations.AddField(
            model_name='user_entry_table',
            name='writing',
            field=models.IntegerField(default=0, verbose_name='写作'),
        ),
    ]
