# Generated by Django 3.2.13 on 2023-06-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230601_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_entry_table',
            name='tran_ans',
            field=models.TextField(default=' ', verbose_name='翻译答案'),
        ),
        migrations.AddField(
            model_name='user_entry_table',
            name='wri_ans',
            field=models.TextField(default=' ', verbose_name='作文答案'),
        ),
    ]
