# Generated by Django 3.0.8 on 2023-06-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230601_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_entry_table',
            name='ID_card',
            field=models.CharField(max_length=18, null=True, verbose_name='身份证号'),
        ),
    ]
