# Generated by Django 3.2.13 on 2023-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230602_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_entry_table',
            name='status',
            field=models.CharField(choices=[('enrolled', '待缴费'), ('payed', '待考试'), ('examed', '待批改'), ('corrected', '已出分')], default='待缴费', max_length=32, verbose_name='考试状态'),
        ),
    ]
