# Generated by Django 3.0.8 on 2023-06-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_entry_table_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_entry_table',
            name='ID_card',
            field=models.CharField(default=' ', max_length=18, verbose_name='身份证号'),
        ),
    ]
