# Generated by Django 3.2.13 on 2023-06-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190517_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('manager', '管理员')], default='学生', max_length=32, verbose_name='用户类型'),
        ),
    ]
